
import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';

const prisma = new PrismaClient();

function escape(val: any): string {
    if (val === null || val === undefined) return 'NULL';
    if (typeof val === 'number') return val.toString();
    if (typeof val === 'boolean') return val ? '1' : '0'; // SQLite uses 1/0 for booleans usually, or string 'true'/'false'. Prisma might expect specific format on re-import but standard SQL uses 1/0 or TRUE/FALSE. Let's use 1/0 for SQLite compatibility.
    if (val instanceof Date) return `'${val.toISOString()}'`; // ISO strings are good for SQLite

    // String escaping
    // Minimal escape for single quotes
    const str = String(val).replace(/'/g, "''").replace(/\n/g, '\\n').replace(/\r/g, '\\r');
    return `'${str}'`;
}

async function backupTable(tableName: string, modelName: string, orderBy: any = undefined) {
    console.log(`Backing up ${tableName}...`);
    // @ts-ignore
    const records = await prisma[modelName].findMany({ orderBy });

    if (records.length === 0) return [];

    const keys = Object.keys(records[0]);
    const columns = keys.join(', ');

    const statements = records.map((record: any) => {
        const values = keys.map(k => escape(record[k])).join(', ');
        return `INSERT INTO "${tableName}" (${columns}) VALUES (${values});`;
    });

    return statements;
}

async function main() {
    try {
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const backupDir = path.join(__dirname, '..', 'backups');

        if (!fs.existsSync(backupDir)) {
            fs.mkdirSync(backupDir);
        }

        const filename = path.join(backupDir, `backup-${timestamp}.sql`);
        const stream = fs.createWriteStream(filename, { flags: 'a' });

        stream.write(`-- Database Backup ${timestamp}\n`);
        stream.write(`-- Generated by backup-db.ts\n\n`);
        stream.write('BEGIN TRANSACTION;\n\n');

        // Order matters for Foreign Keys

        // 1. ItemType
        const itemTypes = await backupTable('ItemType', 'itemType', { id: 'asc' });
        stream.write(`-- Table: ItemType (${itemTypes.length} records)\n`);
        itemTypes.forEach((sql: string) => stream.write(sql + '\n'));
        stream.write('\n');

        // 2. Item
        const items = await backupTable('Item', 'item', { id: 'asc' });
        stream.write(`-- Table: Item (${items.length} records)\n`);
        items.forEach((sql: string) => stream.write(sql + '\n'));
        stream.write('\n');

        // 3. TransactionCategory
        const categories = await backupTable('TransactionCategory', 'transactionCategory', { id: 'asc' });
        stream.write(`-- Table: TransactionCategory (${categories.length} records)\n`);
        categories.forEach((sql: string) => stream.write(sql + '\n'));
        stream.write('\n');

        // 4. ExcelUpload
        const uploads = await backupTable('ExcelUpload', 'excelUpload', { createdAt: 'asc' });
        stream.write(`-- Table: ExcelUpload (${uploads.length} records)\n`);
        uploads.forEach((sql: string) => stream.write(sql + '\n'));
        stream.write('\n');

        // 5. Transaction
        const transactions = await backupTable('Transaction', 'transaction', { fechaValor: 'asc' });
        stream.write(`-- Table: Transaction (${transactions.length} records)\n`);
        transactions.forEach((sql: string) => stream.write(sql + '\n'));
        stream.write('\n');

        stream.write('COMMIT;\n');
        stream.end();

        console.log(`\nBackup completed successfully!`);
        console.log(`File: ${filename}`);
        console.log(`Total sizes:`);
        console.log(`- ItemType: ${itemTypes.length}`);
        console.log(`- Item: ${items.length}`);
        console.log(`- TransactionCategory: ${categories.length}`);
        console.log(`- ExcelUpload: ${uploads.length}`);
        console.log(`- Transaction: ${transactions.length}`);

    } catch (error) {
        console.error('Backup failed:', error);
        process.exit(1);
    } finally {
        await prisma.$disconnect();
    }
}

main();
